### ISSUE TITLE
Exception when trying to create a lambda_policy

### ISSUE THREAD

**Issue by bernardd** [pjodouin/ansible-lambda#13]
Hi there! I'm trying to use lambda_policy.py to create a lambda policy (obviously...). My task looks like this:
```
 - name: Configure Lambda invocation policy 
      lambda_policy: 
        statement_id: "statementID01" 
        function_name: "arn:aws:lambda:us-east-1:773488857071:function:my-function"
        action: lambda:InvokeFunction 
        principal: "s3.amazonaws.com" 
        source_arn: "arn:aws:s3:::my-bucket" 
      become: False 
      delegate_to: localhost  
```
However when I try to run it (with `-vvv`) I get this (edited slightly to remove secrets):
```
TASK [Configure Lambda invocation policy] ****************************************************************************************************************************************************************
task path: /home/ubuntu/playbooks/deploy.yml:266
Using module file /home/ubuntu/playbooks/library/lambda_policy.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXX AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXX /usr/bin/python && sleep 0'
 [WARNING]: Removed unexpected internal key in module return: _ansible_parsed = False

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_6sl2xw/ansible_module_lambda_policy.py", line 496, in <module>
    main()
  File "/tmp/ansible_6sl2xw/ansible_module_lambda_policy.py", line 482, in main
    aws = AWSConnection(module, ['lambda'])
  File "/tmp/ansible_6sl2xw/ansible_module_lambda_policy.py", line 190, in __init__
    self.resource_client[resource] = boto3_conn(ansible_obj, **aws_connect_kwargs)
  File "/tmp/ansible_6sl2xw/ansible_modlib.zip/ansible/module_utils/ec2.py", line 96, in boto3_conn
  File "/tmp/ansible_6sl2xw/ansible_modlib.zip/ansible/module_utils/ec2.py", line 113, in _boto3_conn
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 70, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 224, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 103, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 297, in resolve
    service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python2.7/dist-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

fatal: [app1.mydomain.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_6sl2xw/ansible_module_lambda_policy.py\", line 496, in <module>\n    main()\n  File \"/tmp/ansible_6sl2xw/ansible_module_lambda_policy.py\", line 482, in main\n    aws = AWSConnection(module, ['lambda'])\n  File \"/tmp/ansible_6sl2xw/ansible_module_lambda_policy.py\", line 190, in __init__\n    self.resource_client[resource] = boto3_conn(ansible_obj, **aws_connect_kwargs)\n  File \"/tmp/ansible_6sl2xw/ansible_modlib.zip/ansible/module_utils/ec2.py\", line 96, in boto3_conn\n  File \"/tmp/ansible_6sl2xw/ansible_modlib.zip/ansible/module_utils/ec2.py\", line 113, in _boto3_conn\n  File \"/usr/local/lib/python2.7/dist-packages/boto3/session.py\", line 263, in client\n    aws_session_token=aws_session_token, config=config)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/session.py\", line 836, in create_client\n    client_config=config, api_version=api_version)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 70, in create_client\n    verify, credentials, scoped_config, client_config, endpoint_bridge)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 224, in _get_client_args\n    verify, credentials, scoped_config, client_config, endpoint_bridge)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/args.py\", line 45, in get_client_args\n    endpoint_url, is_secure, scoped_config)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/args.py\", line 103, in compute_client_args\n    service_name, region_name, endpoint_url, is_secure)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 297, in resolve\n    service_name, region_name)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/regions.py\", line 122, in construct_endpoint\n    partition, service_name, region_name)\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/regions.py\", line 135, in _endpoint_for_partition\n    raise NoRegionError()\nbotocore.exceptions.NoRegionError: You must specify a region.\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```
I'm using the development branch of ansible (2.3), in case that's important, since it has the iam_policy module which I also wanted to use.
All my other AWS tasks up to that point are working correctly (including policy, role and lambda function setups), so it's not a general AWS configuration issue. Please let me know if I can provide any more info.

**Comment by pjodouin** [comment]
Hi and thanks for reporting this.  

I see the issue but won't have time to fix it quickly so could you try specifying the region as a module parameter until that time?

```
 - name: Configure Lambda invocation policy 
      lambda_policy: 
        region: us-east-1
        statement_id: "statementID01" 
        function_name: "arn:aws:lambda:us-east-1:773488857071:function:my-function"
```

That should fix it temporarily.  Let me know.

**Comment by bernardd** [comment]
Yep, that got it going - thanks heaps @pjodouin :) (and thanks for the very useful modules).
