### ISSUE TITLE
"NameError : global name 'boto' is not defined" for lambda_fact.py

### ISSUE THREAD

**Issue by plusseed** [pjodouin/ansible-lambda#2]
i using this module, and very thanks.

#### Error
```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/t.shoji/.ansible/tmp/ansible-tmp-1455521903.96-129320106366863/lambda_facts", line 2482, in <module>
    main()
  File "/home/t.shoji/.ansible/tmp/ansible-tmp-1455521903.96-129320106366863/lambda_facts", line 290, in main
    region, endpoint, aws_connect_kwargs = get_aws_connection_info(module, boto3=True)
  File "/home/t.shoji/.ansible/tmp/ansible-tmp-1455521903.96-129320106366863/lambda_facts", line 2390, in get_aws_connection_info
    region = boto.config.get('Boto', 'aws_region')
NameError: global name 'boto' is not defined

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "lambda_facts"}, "parsed": false}
```

#### playbook
```
- name: Lambda Test
  connection: local
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: List all for a specific function
      lambda_facts:
        query: all
        function_name: cycles-export
      register: all_functions
```

#### fix

```
try:
    import boto3
+   import boto
```

There may be other...

**Comment by pjodouin** [comment]
Thank you!

It seems that during the transition from boto to boto3, it's best to include boto as some commits to ansible require it while other times, it's not.  I've updated all modules to import it.
